### ISSUE TITLE
Switch to Mono + DotNetRDF

### ISSUE THREAD

**Issue by calummackervoy** [calummackervoy/SimPolis#1]
Godot is planning to support .NET in 4.1 (https://github.com/godotengine/godot-proposals/issues/2333)

I think that there are some programming reasons to consider using .NET, off the top of my head I'd like to be able to pass delegates around

The main reason for opening this issue however is to get access to an RDF library (https://dotnetrdf.org/). I want to avoid undertaking a GDScript RDF library, and running a Python application alongside the game which acts as a proxy on HTTP requests will probably become unwieldy for any complex and ongoing graph accessing needs

**Comment by Shadowblitz16** [comment]
As long as there is a built in editor for it with the features that the gdscript editor has I support this.

**Comment by aaronfranke** [comment]
@calummackervoy This library supports Mono and .NET Standard https://www.nuget.org/packages/dotNetRDF/ (click "Frameworks") so you can use it with the current C# support in Godot that uses Mono.

**Comment by calummackervoy** [comment]
@aaronfranke thanks! That's really good news
